#!/usr/bin/env bash
set -euo pipefail

mkdir -p /opt/oracle/oradata/recovery_area

LOG_MODE="$(sqlplus -s / as sysdba <<'SQL' | xargs
SET HEADING OFF FEEDBACK OFF PAGESIZE 0 VERIFY OFF ECHO OFF
SELECT LOG_MODE FROM V\$DATABASE;
EXIT;
SQL
)"

if [[ "${LOG_MODE}" != "ARCHIVELOG" ]]; then
  sqlplus -s / as sysdba <<'SQL'
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SYSTEM SET db_recovery_file_dest_size = 5G SCOPE=BOTH;
ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/recovery_area' SCOPE=SPFILE;
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
EXIT;
SQL
fi

sqlplus -s / as sysdba <<'SQL'
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER C##DBZ IDENTIFIED BY DbzPwd123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS CONTAINER=ALL';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION, SET CONTAINER, SELECT ANY TRANSACTION, LOGMINING,
      SELECT ANY DICTIONARY, FLASHBACK ANY TABLE, SELECT ANY TABLE,
      LOCK ANY TABLE, CREATE TABLE, CREATE SEQUENCE
TO C##DBZ CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##DBZ CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##DBZ CONTAINER=ALL;

GRANT SELECT ON V_$DATABASE TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$MYSTAT TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON V_$STATNAME TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON GV_$TRANSACTION TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON GV_$MYSTAT TO C##DBZ CONTAINER=ALL;
GRANT SELECT ON GV_$STATNAME TO C##DBZ CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO C##DBZ CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DBZ CONTAINER=ALL;

ALTER SESSION SET CONTAINER=FREEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER RETAIL IDENTIFIED BY RetailPwd123 QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO RETAIL;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE RETAIL.ORDERS (
      ORDER_ID NUMBER(19) NOT NULL,
      CUSTOMER_ID NUMBER(19) NOT NULL,
      STATUS VARCHAR2(30) NOT NULL,
      TOTAL_CENTS NUMBER(19) NOT NULL,
      VERSION_NO NUMBER(19) DEFAULT 1 NOT NULL,
      UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RETAIL.ORDERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-32588, -1418) THEN RAISE; END IF;
END;
/

GRANT SELECT ON RETAIL.ORDERS TO C##DBZ;
GRANT FLASHBACK ON RETAIL.ORDERS TO C##DBZ;

EXIT;
SQL
